// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjoxkobyevkjcxacfhjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqb3hrb2J5ZXZramN4YWNmaGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTcxNzQsImV4cCI6MjA3MTc5MzE3NH0.-O1iD_oaXZWlXk6gBnvbHTz5y6gNR5ULNgBG-J61OdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});